### ISSUE TITLE
Error: non-zero exit status

### ISSUE THREAD

**Issue by ShalokShalom** [seadanda/protonvpn-applet#12]
```
Traceback (most recent call last):
  File "/usr/bin/protonvpn-applet", line 118, in run
    result = subprocess.check_output(VPNCommand.status.value.split()).decode(sys.stdout.encoding)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', 'protonvpn', 's']' returned non-zero exit status 1.
```

KaOS Linux. KDE Plasma 5, current. How can I help?

**Comment by seadanda** [comment]
Duplicate of issue #11. Closing.
